CREATE TABLE users (
    user_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_fullname VARCHAR(30) NOT NULL,
    user_email VARCHAR(50),
    user_last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);